// archive/old_artifacts_phase0/tools/firebase-quickstart-js/firestore/src/app/app.component.ts
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component } from '@angular/core';
import type { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  constructor(private router: Router) {}
}

<!--
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 -->


<!--
    Router-Outlet is an Angular directive to from the `Router` Library that
    is used to insert the component matched by routes (defined in
    app-routing.module.ts) to be displayed on the screen. See the Angular
    Router docs (https://angular.io/guide/router) for more info.
-->
<router-outlet></router-outlet>

// control/legacy_workspaces/archive_legacy_ShadowTag-v2/apps/devrel-demos/infrastructure/cymbal-toy-store/frontend/src/app/page.tsx
// Copyright 2024 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

"use client";

import Image from "next/image";
import { useRef, useState } from "react";

import Chat from "./chat";
import styles from "./page.module.css";

const items = [
  {
    title: "Baby Bluebird",
    price: "19.99",
    image: "bird",
  },
  {
    title: "Lil' Lamb",
    price: "7.99",
    image: "lamb",
  },
  {
    title: "Allie",
    price: "12.99",
    image: "allie",
  },
  {
    title: "Socks",
    price: "6.99",
    image: "socks",
  },
  {
    title: "Waist belt",
    price: "15.99",
    image: "waistbelt",
  },
  {
    title: "Headband",
    price: "12.99",
    image: "sweatband",
  },
  // {
  //   title: "Wooden Trio",
  //   price: "22.99",
  //   image: "wooden",
  // },
  // {
  //   title: "Slouch",
  //   price: "24.99",
  //   image: "slouch",
  // },
  // {
  //   title: "Splat",
  //   price: "24.99",
  //   image: "splat",
  // },
];

export default function Home() {
  const [chatOpen, setChatOpen] = useState(false);
  const [cartNumber, setCartNumber] = useState(false);
  const textAreaRef = useRef<HTMLTextAreaElement>(null);

  function handleChatClick() {
    if (chatOpen) {
      setChatOpen(false);
    } else {
      setChatOpen(true);
      textAreaRef.current?.focus();
    }
  }

  function handleCallback() {
    setChatOpen(false);
    setCartNumber(true);
  }

  return (
    <main>
      <div className={styles.shipping}>Free shipping on orders over $100</div>
      <div className={styles.menu}>
        <div className={styles.menuInner}>
          <Image alt="logo" src="/logo.svg" width="120" height="50" />
          <div className={styles.cartNumberWrapper}>
            <Image alt="cart" src="/cart.svg" width="30" height="30" />
            {cartNumber && <div className={styles.cartNumber}>1</div>}
          </div>
        </div>
      </div>
      <div className={styles.body}>
        <div>
          <Image alt="toyshop" src="/toyshop.jpg" width="491" height="809" />
        </div>
        <div className={styles.right}>
          <div className={styles.header}>
            <h1>For Kids and Their Parents!</h1>
            <div className={styles.chat} onClick={handleChatClick}>
              <Image alt="open chat" src="/chat.svg" width="30" height="30" />
            </div>
            {<Chat isOpen={chatOpen} callback={handleCallback} textAreaRef={textAreaRef} />}
          </div>
          <div className={styles.grid}>
            {items.map((item) => (
              <div key={item.title} className={styles.item}>
                <Image
                  alt={item.title}
                  className={styles.title}
                  src={`/${item.image}.png`}
                  width="213"
                  height="213"
                />
                <div>{item.title}</div>
                <div>${item.price}</div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  );
}
